//Introdução
Console.WriteLine("Bem vindo! essa é a tabuadas\n");
Console.WriteLine("__________________________________");
Console.WriteLine("Tabuada do 1");
int numero1 = 1 * 1;
Console.WriteLine($"A tabuada de 1 * 1 = {numero1}");
int numero2 = 1 * 2;
Console.WriteLine($"A tabuada de 1 * 2 = {numero2}");
int numero3 = 1 * 3;
Console.WriteLine($"A tabuada de 1 * 3 = {numero3}");
int numero4 = 1 * 4;
Console.WriteLine($"A tabuada de 1 * 4 = {numero4}");
int numero5 = 1 * 5;
Console.WriteLine($"A tabuada de 1 * 5 = {numero5}");
int numero6 = 1 * 6;
Console.WriteLine($"A tabuada de 1 * 6 = {numero6}");
int numero7 = 1 * 7;
Console.WriteLine($"A tabuada de 1 * 7 = {numero7}");
int numero8 = 1 * 8;
Console.WriteLine($"A tabuada de 1 * 8 = {numero8}");
int numero9 = 1 * 9;
Console.WriteLine($"A tabuada de 1 * 9 = {numero9}");
int numero10 = 1 * 10;
Console.WriteLine($"A tabuada de 1 * 10 = {numero10}");
Console.WriteLine("__________________________________");
Console.WriteLine("Tabuada do 2");
int numero11 = 2 * 1;
Console.WriteLine($"A tabuada de 2 * 1 = {numero11}");
int numero12 = 2 * 2;
Console.WriteLine($"A tabuada de 2 * 2 = {numero12}");
int numero13 = 2 * 3;
Console.WriteLine($"A tabuada de 2 * 3 = {numero13}");
int numero14 = 2 * 4;
Console.WriteLine($"A tabuada de 2 * 4 = {numero14}");
int numero15 = 2 * 5;
Console.WriteLine($"A tabuada de 2 * 5 = {numero15}");
int numero16 = 2 * 6;
Console.WriteLine($"A tabuada de 2 * 6 = {numero16}");
int numero17 = 2 * 7;
Console.WriteLine($"A tabuada de 2 * 7 = {numero17}");
int numero18 = 2 * 8;
Console.WriteLine($"A tabuada de 2 * 8 = {numero18}");
int numero19 = 2 * 9;
Console.WriteLine($"A tabuada de 2 * 9 = {numero19}");
int numero20 = 2 * 10;
Console.WriteLine($"A tabuada de 2 * 10 = {numero20}");
Console.WriteLine("__________________________________");
Console.WriteLine("Tabuada do 3");
int numero21 = 3 * 1;
Console.WriteLine($"A tabuada de 3 * 1 = {numero21}");
int numero22 = 3 * 2;
Console.WriteLine($"A tabuada de 3 * 2 = {numero22}");
int numero23 = 3 * 3;
Console.WriteLine($"A tabuada de 3 * 3 = {numero23}");
int numero24 = 3 * 4;
Console.WriteLine($"A tabuada de 3 * 4 = {numero24}");
int numero25 = 3 * 5;
Console.WriteLine($"A tabuada de 3 * 5 = {numero25}");
int numero26 = 3 * 6;
Console.WriteLine($"A tabuada de 3 * 6 = {numero26}");
int numero27 = 3 * 7;
Console.WriteLine($"A tabuada de 3 * 7 = {numero27}");
int numero28 = 3 * 8;
Console.WriteLine($"A tabuada de 3 * 8 = {numero28}");
int numero29 = 3 * 9;
Console.WriteLine($"A tabuada de 3 * 9 = {numero29}");
int numero30 = 3 * 10;
Console.WriteLine($"A tabuada de 3 * 10 = {numero30}");
Console.WriteLine("__________________________________");
Console.WriteLine("Tabuada do 4");
int numero31 = 4 * 1;
Console.WriteLine($"A tabuada de 4 * 1 = {numero31}");
int numero32 = 4 * 2;
Console.WriteLine($"A tabuada de 4 * 2 = {numero32}");
int numero33 = 4 * 3;
Console.WriteLine($"A tabuada de 4 * 3 = {numero33}");
int numero34 = 4 * 4;
Console.WriteLine($"A tabuada de 4 * 4 = {numero34}");
int numero35 = 4 * 5;
Console.WriteLine($"A tabuada de 4 * 5 = {numero35}");
int numero36 = 4 * 6;
Console.WriteLine($"A tabuada de 4 * 6 = {numero36}");
int numero37 = 4 * 7;
Console.WriteLine($"A tabuada de 4 * 7 = {numero37}");
int numero38 = 4 * 8;
Console.WriteLine($"A tabuada de 4 * 8 = {numero38}");
int numero39 = 4 * 9;
Console.WriteLine($"A tabuada de 4 * 9 = {numero39}");
int numero40 = 4 * 10;
Console.WriteLine($"A tabuada de 4 * 10 = {numero40}");
Console.WriteLine("__________________________________");
Console.WriteLine("Tabuada do 5");
int numero41 = 5 * 1;
Console.WriteLine($"A tabuada de 5 * 1 = {numero41}");
int numero42 = 5 * 2;
Console.WriteLine($"A tabuada de 5 * 2 = {numero42}");
int numero43 = 5 * 3;
Console.WriteLine($"A tabuada de 5 * 3 = {numero43}");
int numero44 = 5 * 4;
Console.WriteLine($"A tabuada de 5 * 4 = {numero44}");
int numero45 = 5 * 5;
Console.WriteLine($"A tabuada de 5 * 5 = {numero45}");
int numero46 = 5 * 6;
Console.WriteLine($"A tabuada de 5 * 6 = {numero46}");
int numero47 = 5 * 7;
Console.WriteLine($"A tabuada de 5 * 7 = {numero47}");
int numero48 = 5 * 8;
Console.WriteLine($"A tabuada de 5 * 8 = {numero48}");
int numero49 = 5 * 9;
Console.WriteLine($"A tabuada de 5 * 9 = {numero49}");
int numero50 = 5 * 10;
Console.WriteLine($"A tabuada de 5 * 10 = {numero50}");
Console.WriteLine("__________________________________");
Console.WriteLine("Tabuada do 6");
int numero51 = 6 * 1;
Console.WriteLine($"A tabuada de 6 * 1 = {numero51}");
int numero52 = 6 * 2;
Console.WriteLine($"A tabuada de 6 * 2 = {numero52}");
int numero53 = 6 * 3;
Console.WriteLine($"A tabuada de 6 * 3 = {numero53}");
int numero54 = 6 * 4;
Console.WriteLine($"A tabuada de 6 * 4 = {numero54}");
int numero55 = 6 * 5;
Console.WriteLine($"A tabuada de 6 * 5 = {numero55}");
int numero56 = 6 * 6;
Console.WriteLine($"A tabuada de 6 * 6 = {numero56}");
int numero57 = 6 * 7;
Console.WriteLine($"A tabuada de 6 * 7 = {numero57}");
int numero58 = 6 * 8;
Console.WriteLine($"A tabuada de 6 * 8 = {numero58}");
int numero59 = 6 * 9;
Console.WriteLine($"A tabuada de 6 * 9 = {numero59}");
int numero60 = 6 * 10;
Console.WriteLine($"A tabuada de 6 * 10 = {numero60}");
Console.WriteLine("__________________________________");
Console.WriteLine("Tabuada do 7");
int numero61 = 7 * 1;
Console.WriteLine($"A tabuada de 7 * 1 = {numero61}");
int numero62 = 7 * 2;
Console.WriteLine($"A tabuada de 7 * 2 = {numero62}");
int numero63 = 7 * 3;
Console.WriteLine($"A tabuada de 7 * 3 = {numero63}");
int numero64 = 7 * 4;
Console.WriteLine($"A tabuada de 7 * 4 = {numero64}");
int numero65 = 7 * 5;
Console.WriteLine($"A tabuada de 7 * 5 = {numero65}");
int numero66 = 7 * 6;
Console.WriteLine($"A tabuada de 7 * 6 = {numero66}");
int numero67 = 7 * 7;
Console.WriteLine($"A tabuada de 7 * 7 = {numero67}");
int numero68 = 7 * 8;
Console.WriteLine($"A tabuada de 7 * 8 = {numero68}");
int numero69 = 7 * 9;
Console.WriteLine($"A tabuada de 7 * 9 = {numero69}");
int numero70 = 7 * 10;
Console.WriteLine($"A tabuada de 7 * 10 = {numero70}");
Console.WriteLine("__________________________________");
Console.WriteLine("Tabuada do 8");
int numero71 = 8 * 1;
Console.WriteLine($"A tabuada de 8 * 1 = {numero71}");
int numero72 = 8 * 2;
Console.WriteLine($"A tabuada de 8 * 2 = {numero72}");
int numero73 = 8 * 3;
Console.WriteLine($"A tabuada de 8 * 3 = {numero73}");
int numero74 = 8 * 4; 
Console.WriteLine($"A tabuada de 8 * 4 = {numero74}");
int numero75 = 8 * 5;
Console.WriteLine($"A tabuada de 8 * 5 = {numero75}");
int numero76 = 8 * 6;
Console.WriteLine($"A tabuada de 8 * 6 = {numero76}");
int numero77 = 8 * 7;
Console.WriteLine($"A tabuada de 8 * 7 = {numero77}");
int numero78 = 8 * 8;
Console.WriteLine($"A tabuada de 8 * 8 = {numero78}");
int numero79 = 8 * 9;
Console.WriteLine($"A tabuada de 8 * 9 = {numero79}");
int numero80 = 8 * 10;
Console.WriteLine($"A tabuada de 8 * 10 = {numero80}");
Console.WriteLine("__________________________________");
Console.WriteLine("Tabuada do 9");
int numero81 = 9 * 1;
Console.WriteLine($"A tabuada de 9 * 1 = {numero81}");
int numero82 = 9 * 2;
Console.WriteLine($"A tabuada de 9 * 2 = {numero82}");
int numero83 = 9 * 3;
Console.WriteLine($"A tabuada de 9 * 3 = {numero83}");
int numero84 = 9 * 4;
Console.WriteLine($"A tabuada de 9 * 4 = {numero84}");
int numero85 = 9 * 5;
Console.WriteLine($"A tabuada de 9 * 5 = {numero85}");
int numero86 = 9 * 6;
Console.WriteLine($"A tabuada de 9 * 6 = {numero86}");
int numero87 = 9 * 7;
Console.WriteLine($"A tabuada de 9 * 7 = {numero87}");
int numero88 = 9 * 8;
Console.WriteLine($"A tabuada de 9 * 8 = {numero88}");
int numero89 = 9 * 9;
Console.WriteLine($"A tabuada de 9 * 9 = {numero89}");
int numero90 = 9 * 10;
Console.WriteLine($"A tabuada de 9 * 10 = {numero90}");
Console.WriteLine("__________________________________");
Console.WriteLine("Tabuada do 10");
int numero91 = 10 * 1;
Console.WriteLine($"A tabuada de 10 * 1 = {numero91}");
int numero92 = 10 * 2;
Console.WriteLine($"A tabuada de 10 * 2 = {numero92}");
int numero93 = 10 * 3;
Console.WriteLine($"A tabuada de 10 * 3 = {numero93}");
int numero94 = 10 * 4;
Console.WriteLine($"A tabuada de 10 * 4 = {numero94}");
int numero95 = 10 * 5;
Console.WriteLine($"A tabuada de 10 * 5 = {numero95}");
int numero96 = 10 * 6;
Console.WriteLine($"A tabuada de 10 * 6 = {numero96}");
int numero97 = 10 * 7;
Console.WriteLine($"A tabuada de 10 * 7 = {numero97}");
int numero98 = 10 * 8;
Console.WriteLine($"A tabuada de 10 * 8 = {numero98}");
int numero99 = 10 * 9;
Console.WriteLine($"A tabuada de 10 * 9 = {numero99}");
int numero100 = 10 * 10;
Console.WriteLine($"A tabuada de 10 * 10 = {numero100}");
